def Excel_Save(tt92, tt96, tt961, tt98, HowMany, GroupName, boxes, data01, data01Stamp, data02, data02Stamp, data03, data03Stamp, data04, data04Stamp, data05, data05Stamp, data06, data06Stamp, data07, data07Stamp, data08, data08Stamp, data09, data09Stamp, data10, data10Stamp, data11, data11Stamp, data12, data12Stamp, data13, data13Stamp, data14, data14Stamp, data15, data15Stamp, data16, data16Stamp, data17, data17Stamp, data18, data18Stamp, data19, data19Stamp, data20, data20Stamp, data21, data21Stamp, data22, data22Stamp, data23, data23Stamp, data24, data24Stamp, Tank0108, Tank0916, Tank1724, Tank25, OnLineTracking):
    import xlwt
    import xlsxwriter
    import time
    from PIL import ImageGrab
    #book = xlwt.Workbook(encoding="utf-8")
    book = xlsxwriter.Workbook("D:\\Vertical Assay\\EMBLarval_Excel\\" + GroupName + "\\TrackingData_" + GroupName + "_" + tt961 + "_" + ('%04d' % tt96) + "_Raw.xlsx")

    ComputerName = "Administrator"
    #ComputerName = "RueyToshiba"
    if int(HowMany) > 1:
        if OnLineTracking == 2:
            sheet1 = book.add_worksheet("Tank01")
            Tank0108.release()
            Tank0916.release()
            Tank1724.release()
            Tank25.release()
            del Tank0108
            del Tank0916
            del Tank1724
            del Tank25
        else:
            sheet1 = book.add_worksheet("Tank01")
            if int(HowMany) > 2:
                sheet2 = book.add_worksheet("Tank02")
                if int(HowMany) > 3:
                    sheet3 = book.add_worksheet("Tank03")
                    if int(HowMany) > 4:
                        sheet4 = book.add_worksheet("Tank04")
                        if int(HowMany) > 5:
                            sheet5 = book.add_worksheet("Tank05")
                            if int(HowMany) > 6:
                                sheet6 = book.add_worksheet("Tank06")
                                if int(HowMany) > 7:
                                    sheet7 = book.add_worksheet("Tank07")
                                    if int(HowMany) > 8:
                                        sheet8 = book.add_worksheet("Tank08")
                                        if int(HowMany) > 9:
                                            sheet9 = book.add_worksheet("Tank09")
                                            if int(HowMany) > 10:
                                                sheet10 = book.add_worksheet("Tank10")
                                                if int(HowMany) > 11:
                                                    sheet11 = book.add_worksheet("Tank11")
                                                    if int(HowMany) > 12:
                                                        sheet12 = book.add_worksheet("Tank12")
                                                        if int(HowMany) > 13:
                                                            sheet13 = book.add_worksheet("Tank13")
                                                            if int(HowMany) > 14:
                                                                sheet14 = book.add_worksheet("Tank14")
                                                                if int(HowMany) > 15:
                                                                    sheet15 = book.add_worksheet("Tank15")
                                                                    if int(HowMany) > 16:
                                                                        sheet16 = book.add_worksheet("Tank16")
                                                                        if int(HowMany) > 17:
                                                                            sheet17 = book.add_worksheet("Tank17")
                                                                            if int(HowMany) > 18:
                                                                                sheet18 = book.add_worksheet("Tank18")
                                                                                if int(HowMany) > 19:
                                                                                    sheet19 = book.add_worksheet("Tank19")
                                                                                    if int(HowMany) > 20:
                                                                                        sheet20 = book.add_worksheet("Tank20")
                                                                                        if int(HowMany) > 21:
                                                                                            sheet21 = book.add_worksheet("Tank21")
                                                                                            if int(HowMany) > 22:
                                                                                                sheet22 = book.add_worksheet("Tank22")
                                                                                                if int(HowMany) > 23:
                                                                                                    sheet23 = book.add_worksheet("Tank23")
                                                                                                    if int(HowMany) > 24:
                                                                                                        sheet24 = book.add_worksheet("Tank24")
                                                                                                    Tank0108.release()
                                                                                                    Tank0916.release()
                                                                                                    Tank1724.release()
                                                                                                    Tank25.release()
                                                                                                    del Tank0108
                                                                                                    del Tank0916
                                                                                                    del Tank1724
                                                                                                    del Tank25
                                                                                                                                                                                                    
    rows = len(data01)
    if int(HowMany) > 1:
        sheet1.write(0, 0, 'Exp Time')
        sheet1.write(0, 1, time.ctime())
        sheet1.write(1, 0, 'Tank #')
        sheet1.write(1, 1, '1')
        sheet1.write(2, 0, 'Fish Group')
        sheet1.write(3, 0, 'Fish ID')
        sheet1.write(4, 0, 'Fish DOB')
        sheet1.write(5, 0, 'Tank-P1')
        sheet1.write(5, 2, boxes[0][0])
        sheet1.write(5, 3, boxes[0][1])
        sheet1.write(6, 0, 'Tank-P2')
        sheet1.write(6, 2, boxes[1][0])
        sheet1.write(6, 3, boxes[1][1])
        sheet1.write(8, 0, 'x-y coordinates')
        sheet1.write(9, 0, 'Frame #')
        sheet1.write(9, 1, 'Timestamp')
        sheet1.write(9, 2, 'fish-x')
        sheet1.write(9, 3, 'fish-y')
        sheet1.write(9, 4, 'x')
        sheet1.write(9, 5, 'y')
        sheet1.write(9, 6, 'w')
        sheet1.write(9, 7, 'h')

    if OnLineTracking == 2:
        pass
    else:
        if int(HowMany) > 2:
            sheet2.write(0, 0, 'Exp Time')
            sheet2.write(0, 1, time.ctime())
            sheet2.write(1, 0, 'Tank #')
            sheet2.write(1, 1, '2')
            sheet2.write(2, 0, 'Fish Group')
            sheet2.write(3, 0, 'Fish ID')
            sheet2.write(4, 0, 'Fish DOB')
            sheet2.write(5, 0, 'Tank-P1')
            sheet2.write(5, 2, boxes[2][0])
            sheet2.write(5, 3, boxes[2][1])
            sheet2.write(6, 0, 'Tank-P2')
            sheet2.write(6, 2, boxes[3][0])
            sheet2.write(6, 3, boxes[3][1])
            sheet2.write(8, 0, 'x-y coordinates')
            sheet2.write(9, 0, 'Frame #')
            sheet2.write(9, 1, 'Timestamp')
            sheet2.write(9, 2, 'fish-x')
            sheet2.write(9, 3, 'fish-y')
            sheet2.write(9, 4, 'x')
            sheet2.write(9, 5, 'y')
            sheet2.write(9, 6, 'w')
            sheet2.write(9, 7, 'h')

        if int(HowMany) > 3:
            sheet3.write(0, 0, 'Exp Time')
            sheet3.write(0, 1, time.ctime())
            sheet3.write(1, 0, 'Tank #')
            sheet3.write(1, 1, '3')
            sheet3.write(2, 0, 'Fish Group')
            sheet3.write(3, 0, 'Fish ID')
            sheet3.write(4, 0, 'Fish DOB')
            sheet3.write(5, 0, 'Tank-P1')
            sheet3.write(5, 2, boxes[4][0])
            sheet3.write(5, 3, boxes[4][1])
            sheet3.write(6, 0, 'Tank-P2')
            sheet3.write(6, 2, boxes[5][0])
            sheet3.write(6, 3, boxes[5][1])
            sheet3.write(8, 0, 'x-y coordinates')
            sheet3.write(9, 0, 'Frame #')
            sheet3.write(9, 1, 'Timestamp')
            sheet3.write(9, 2, 'fish-x')
            sheet3.write(9, 3, 'fish-y')
            sheet3.write(9, 4, 'x')
            sheet3.write(9, 5, 'y')
            sheet3.write(9, 6, 'w')
            sheet3.write(9, 7, 'h')
        if int(HowMany) > 4:
            sheet4.write(0, 0, 'Exp Time')
            sheet4.write(0, 1, time.ctime())
            sheet4.write(1, 0, 'Tank #')
            sheet4.write(1, 1, '4')
            sheet4.write(2, 0, 'Fish Group')
            sheet4.write(3, 0, 'Fish ID')
            sheet4.write(4, 0, 'Fish DOB')
            sheet4.write(5, 0, 'Tank-P1')
            sheet4.write(5, 2, boxes[6][0])
            sheet4.write(5, 3, boxes[6][1])
            sheet4.write(6, 0, 'Tank-P2')
            sheet4.write(6, 2, boxes[7][0])
            sheet4.write(6, 3, boxes[7][1])
            sheet4.write(8, 0, 'x-y coordinates')
            sheet4.write(9, 0, 'Frame #')
            sheet4.write(9, 1, 'Timestamp')
            sheet4.write(9, 2, 'fish-x')
            sheet4.write(9, 3, 'fish-y')
            sheet4.write(9, 4, 'x')
            sheet4.write(9, 5, 'y')
            sheet4.write(9, 6, 'w')
            sheet4.write(9, 7, 'h')

        if int(HowMany) > 5:
            sheet5.write(0, 0, 'Exp Time')
            sheet5.write(0, 1, time.ctime())
            sheet5.write(1, 0, 'Tank #')
            sheet5.write(1, 1, '5')
            sheet5.write(2, 0, 'Fish Group')
            sheet5.write(3, 0, 'Fish ID')
            sheet5.write(4, 0, 'Fish DOB')
            sheet5.write(5, 0, 'Tank-P1')
            sheet5.write(5, 2, boxes[8][0])
            sheet5.write(5, 3, boxes[8][1])
            sheet5.write(6, 0, 'Tank-P2')
            sheet5.write(6, 2, boxes[9][0])
            sheet5.write(6, 3, boxes[9][1])
            sheet5.write(8, 0, 'x-y coordinates')
            sheet5.write(9, 0, 'Frame #')
            sheet5.write(9, 1, 'Timestamp')
            sheet5.write(9, 2, 'fish-x')
            sheet5.write(9, 3, 'fish-y')
            sheet5.write(9, 4, 'x')
            sheet5.write(9, 5, 'y')
            sheet5.write(9, 6, 'w')
            sheet5.write(9, 7, 'h')

        if int(HowMany) > 6:
            sheet6.write(0, 0, 'Exp Time')
            sheet6.write(0, 1, time.ctime())
            sheet6.write(1, 0, 'Tank #')
            sheet6.write(1, 1, '6')
            sheet6.write(2, 0, 'Fish Group')
            sheet6.write(3, 0, 'Fish ID')
            sheet6.write(4, 0, 'Fish DOB')
            sheet6.write(5, 0, 'Tank-P1')
            sheet6.write(5, 2, boxes[10][0])
            sheet6.write(5, 3, boxes[10][1])
            sheet6.write(6, 0, 'Tank-P2')
            sheet6.write(6, 2, boxes[11][0])
            sheet6.write(6, 3, boxes[11][1])
            sheet6.write(8, 0, 'x-y coordinates')
            sheet6.write(9, 0, 'Frame #')
            sheet6.write(9, 1, 'Timestamp')
            sheet6.write(9, 2, 'fish-x')
            sheet6.write(9, 3, 'fish-y')
            sheet6.write(9, 4, 'x')
            sheet6.write(9, 5, 'y')
            sheet6.write(9, 6, 'w')
            sheet6.write(9, 7, 'h')

        if int(HowMany) > 7:
            sheet7.write(0, 0, 'Exp Time')
            sheet7.write(0, 1, time.ctime())
            sheet7.write(1, 0, 'Tank #')
            sheet7.write(1, 1, '7')
            sheet7.write(2, 0, 'Fish Group')
            sheet7.write(3, 0, 'Fish ID')
            sheet7.write(4, 0, 'Fish DOB')
            sheet7.write(5, 0, 'Tank-P1')
            sheet7.write(5, 2, boxes[12][0])
            sheet7.write(5, 3, boxes[12][1])
            sheet7.write(6, 0, 'Tank-P2')
            sheet7.write(6, 2, boxes[13][0])
            sheet7.write(6, 3, boxes[13][1])
            sheet7.write(8, 0, 'x-y coordinates')
            sheet7.write(9, 0, 'Frame #')
            sheet7.write(9, 1, 'Timestamp')
            sheet7.write(9, 2, 'fish-x')
            sheet7.write(9, 3, 'fish-y')
            sheet7.write(9, 4, 'x')
            sheet7.write(9, 5, 'y')
            sheet7.write(9, 6, 'w')
            sheet7.write(9, 7, 'h')

        if int(HowMany) > 8:
            sheet8.write(0, 0, 'Exp Time')
            sheet8.write(0, 1, time.ctime())
            sheet8.write(1, 0, 'Tank #')
            sheet8.write(1, 1, '8')
            sheet8.write(2, 0, 'Fish Group')
            sheet8.write(3, 0, 'Fish ID')
            sheet8.write(4, 0, 'Fish DOB')
            sheet8.write(5, 0, 'Tank-P1')
            sheet8.write(5, 2, boxes[14][0])
            sheet8.write(5, 3, boxes[14][1])
            sheet8.write(6, 0, 'Tank-P2')
            sheet8.write(6, 2, boxes[15][0])
            sheet8.write(6, 3, boxes[15][1])
            sheet8.write(8, 0, 'x-y coordinates')
            sheet8.write(9, 0, 'Frame #')
            sheet8.write(9, 1, 'Timestamp')
            sheet8.write(9, 2, 'fish-x')
            sheet8.write(9, 3, 'fish-y')
            sheet8.write(9, 4, 'x')
            sheet8.write(9, 5, 'y')
            sheet8.write(9, 6, 'w')
            sheet8.write(9, 7, 'h')

        if int(HowMany) > 9:
            sheet9.write(0, 0, 'Exp Time')
            sheet9.write(0, 1, time.ctime())
            sheet9.write(1, 0, 'Tank #')
            sheet9.write(1, 1, '9')
            sheet9.write(2, 0, 'Fish Group')
            sheet9.write(3, 0, 'Fish ID')
            sheet9.write(4, 0, 'Fish DOB')
            sheet9.write(5, 0, 'Tank-P1')
            sheet9.write(5, 2, boxes[16][0])
            sheet9.write(5, 3, boxes[16][1])
            sheet9.write(6, 0, 'Tank-P2')
            sheet9.write(6, 2, boxes[17][0])
            sheet9.write(6, 3, boxes[17][1])
            sheet9.write(8, 0, 'x-y coordinates')
            sheet9.write(9, 0, 'Frame #')
            sheet9.write(9, 1, 'Timestamp')
            sheet9.write(9, 2, 'fish-x')
            sheet9.write(9, 3, 'fish-y')
            sheet9.write(9, 4, 'x')
            sheet9.write(9, 5, 'y')
            sheet9.write(9, 6, 'w')
            sheet9.write(9, 7, 'h')

        if int(HowMany) > 10:
            sheet10.write(0, 0, 'Exp Time')
            sheet10.write(0, 1, time.ctime())
            sheet10.write(1, 0, 'Tank #')
            sheet10.write(1, 1, '10')
            sheet10.write(2, 0, 'Fish Group')
            sheet10.write(3, 0, 'Fish ID')
            sheet10.write(4, 0, 'Fish DOB')
            sheet10.write(5, 0, 'Tank-P1')
            sheet10.write(5, 2, boxes[18][0])
            sheet10.write(5, 3, boxes[18][1])
            sheet10.write(6, 0, 'Tank-P2')
            sheet10.write(6, 2, boxes[19][0])
            sheet10.write(6, 3, boxes[19][1])
            sheet10.write(8, 0, 'x-y coordinates')
            sheet10.write(9, 0, 'Frame #')
            sheet10.write(9, 1, 'Timestamp')
            sheet10.write(9, 2, 'fish-x')
            sheet10.write(9, 3, 'fish-y')
            sheet10.write(9, 4, 'x')
            sheet10.write(9, 5, 'y')
            sheet10.write(9, 6, 'w')
            sheet10.write(9, 7, 'h')

        if int(HowMany) > 11:
            sheet11.write(0, 0, 'Exp Time')
            sheet11.write(0, 1, time.ctime())
            sheet11.write(1, 0, 'Tank #')
            sheet11.write(1, 1, '11')
            sheet11.write(2, 0, 'Fish Group')
            sheet11.write(3, 0, 'Fish ID')
            sheet11.write(4, 0, 'Fish DOB')
            sheet11.write(5, 0, 'Tank-P1')
            sheet11.write(5, 2, boxes[20][0])
            sheet11.write(5, 3, boxes[20][1])
            sheet11.write(6, 0, 'Tank-P2')
            sheet11.write(6, 2, boxes[21][0])
            sheet11.write(6, 3, boxes[21][1])
            sheet11.write(8, 0, 'x-y coordinates')
            sheet11.write(9, 0, 'Frame #')
            sheet11.write(9, 1, 'Timestamp')
            sheet11.write(9, 2, 'fish-x')
            sheet11.write(9, 3, 'fish-y')
            sheet11.write(9, 4, 'x')
            sheet11.write(9, 5, 'y')
            sheet11.write(9, 6, 'w')
            sheet11.write(9, 7, 'h')

        if int(HowMany) > 12:
            sheet12.write(0, 0, 'Exp Time')
            sheet12.write(0, 1, time.ctime())
            sheet12.write(1, 0, 'Tank #')
            sheet12.write(1, 1, '12')
            sheet12.write(2, 0, 'Fish Group')
            sheet12.write(3, 0, 'Fish ID')
            sheet12.write(4, 0, 'Fish DOB')
            sheet12.write(5, 0, 'Tank-P1')
            sheet12.write(5, 2, boxes[22][0])
            sheet12.write(5, 3, boxes[22][1])
            sheet12.write(6, 0, 'Tank-P2')
            sheet12.write(6, 2, boxes[23][0])
            sheet12.write(6, 3, boxes[23][1])
            sheet12.write(8, 0, 'x-y coordinates')
            sheet12.write(9, 0, 'Frame #')
            sheet12.write(9, 1, 'Timestamp')
            sheet12.write(9, 2, 'fish-x')
            sheet12.write(9, 3, 'fish-y')
            sheet12.write(9, 4, 'x')
            sheet12.write(9, 5, 'y')
            sheet12.write(9, 6, 'w')
            sheet12.write(9, 7, 'h')

        if int(HowMany) > 13:
            sheet13.write(0, 0, 'Exp Time')
            sheet13.write(0, 1, time.ctime())
            sheet13.write(1, 0, 'Tank #')
            sheet13.write(1, 1, '13')
            sheet13.write(2, 0, 'Fish Group')
            sheet13.write(3, 0, 'Fish ID')
            sheet13.write(4, 0, 'Fish DOB')
            sheet13.write(5, 0, 'Tank-P1')
            sheet13.write(5, 2, boxes[24][0])
            sheet13.write(5, 3, boxes[24][1])
            sheet13.write(6, 0, 'Tank-P2')
            sheet13.write(6, 2, boxes[25][0])
            sheet13.write(6, 3, boxes[25][1])
            sheet13.write(8, 0, 'x-y coordinates')
            sheet13.write(9, 0, 'Frame #')
            sheet13.write(9, 1, 'Timestamp')
            sheet13.write(9, 2, 'fish-x')
            sheet13.write(9, 3, 'fish-y')
            sheet13.write(9, 4, 'x')
            sheet13.write(9, 5, 'y')
            sheet13.write(9, 6, 'w')
            sheet13.write(9, 7, 'h')

        if int(HowMany) > 14:
            sheet14.write(0, 0, 'Exp Time')
            sheet14.write(0, 1, time.ctime())
            sheet14.write(1, 0, 'Tank #')
            sheet14.write(1, 1, '14')
            sheet14.write(2, 0, 'Fish Group')
            sheet14.write(3, 0, 'Fish ID')
            sheet14.write(4, 0, 'Fish DOB')
            sheet14.write(5, 0, 'Tank-P1')
            sheet14.write(5, 2, boxes[26][0])
            sheet14.write(5, 3, boxes[26][1])
            sheet14.write(6, 0, 'Tank-P2')
            sheet14.write(6, 2, boxes[27][0])
            sheet14.write(6, 3, boxes[27][1])
            sheet14.write(8, 0, 'x-y coordinates')
            sheet14.write(9, 0, 'Frame #')
            sheet14.write(9, 1, 'Timestamp')
            sheet14.write(9, 2, 'fish-x')
            sheet14.write(9, 3, 'fish-y')
            sheet14.write(9, 4, 'x')
            sheet14.write(9, 5, 'y')
            sheet14.write(9, 6, 'w')
            sheet14.write(9, 7, 'h')

        if int(HowMany) > 15:
            sheet15.write(0, 0, 'Exp Time')
            sheet15.write(0, 1, time.ctime())
            sheet15.write(1, 0, 'Tank #')
            sheet15.write(1, 1, '15')
            sheet15.write(2, 0, 'Fish Group')
            sheet15.write(3, 0, 'Fish ID')
            sheet15.write(4, 0, 'Fish DOB')
            sheet15.write(5, 0, 'Tank-P1')
            sheet15.write(5, 2, boxes[28][0])
            sheet15.write(5, 3, boxes[28][1])
            sheet15.write(6, 0, 'Tank-P2')
            sheet15.write(6, 2, boxes[29][0])
            sheet15.write(6, 3, boxes[29][1])
            sheet15.write(8, 0, 'x-y coordinates')
            sheet15.write(9, 0, 'Frame #')
            sheet15.write(9, 1, 'Timestamp')
            sheet15.write(9, 2, 'fish-x')
            sheet15.write(9, 3, 'fish-y')
            sheet15.write(9, 4, 'x')
            sheet15.write(9, 5, 'y')
            sheet15.write(9, 6, 'w')
            sheet15.write(9, 7, 'h')

        if int(HowMany) > 16:
            sheet16.write(0, 0, 'Exp Time')
            sheet16.write(0, 1, time.ctime())
            sheet16.write(1, 0, 'Tank #')
            sheet16.write(1, 1, '16')
            sheet16.write(2, 0, 'Fish Group')
            sheet16.write(3, 0, 'Fish ID')
            sheet16.write(4, 0, 'Fish DOB')
            sheet16.write(5, 0, 'Tank-P1')
            sheet16.write(5, 2, boxes[30][0])
            sheet16.write(5, 3, boxes[30][1])
            sheet16.write(6, 0, 'Tank-P2')
            sheet16.write(6, 2, boxes[31][0])
            sheet16.write(6, 3, boxes[31][1])
            sheet16.write(8, 0, 'x-y coordinates')
            sheet16.write(9, 0, 'Frame #')
            sheet16.write(9, 1, 'Timestamp')
            sheet16.write(9, 2, 'fish-x')
            sheet16.write(9, 3, 'fish-y')
            sheet16.write(9, 4, 'x')
            sheet16.write(9, 5, 'y')
            sheet16.write(9, 6, 'w')
            sheet16.write(9, 7, 'h')

        if int(HowMany) > 17:
            sheet17.write(0, 0, 'Exp Time')
            sheet17.write(0, 1, time.ctime())
            sheet17.write(1, 0, 'Tank #')
            sheet17.write(1, 1, '17')
            sheet17.write(2, 0, 'Fish Group')
            sheet17.write(3, 0, 'Fish ID')
            sheet17.write(4, 0, 'Fish DOB')
            sheet17.write(5, 0, 'Tank-P1')
            sheet17.write(5, 2, boxes[32][0])
            sheet17.write(5, 3, boxes[32][1])
            sheet17.write(6, 0, 'Tank-P2')
            sheet17.write(6, 2, boxes[33][0])
            sheet17.write(6, 3, boxes[33][1])
            sheet17.write(8, 0, 'x-y coordinates')
            sheet17.write(9, 0, 'Frame #')
            sheet17.write(9, 1, 'Timestamp')
            sheet17.write(9, 2, 'fish-x')
            sheet17.write(9, 3, 'fish-y')
            sheet17.write(9, 4, 'x')
            sheet17.write(9, 5, 'y')
            sheet17.write(9, 6, 'w')
            sheet17.write(9, 7, 'h')

        if int(HowMany) > 18:
            sheet18.write(0, 0, 'Exp Time')
            sheet18.write(0, 1, time.ctime())
            sheet18.write(1, 0, 'Tank #')
            sheet18.write(1, 1, '16')
            sheet18.write(2, 0, 'Fish Group')
            sheet18.write(3, 0, 'Fish ID')
            sheet18.write(4, 0, 'Fish DOB')
            sheet18.write(5, 0, 'Tank-P1')
            sheet18.write(5, 2, boxes[34][0])
            sheet18.write(5, 3, boxes[34][1])
            sheet18.write(6, 0, 'Tank-P2')
            sheet18.write(6, 2, boxes[35][0])
            sheet18.write(6, 3, boxes[35][1])
            sheet18.write(8, 0, 'x-y coordinates')
            sheet18.write(9, 0, 'Frame #')
            sheet18.write(9, 1, 'Timestamp')
            sheet18.write(9, 2, 'fish-x')
            sheet18.write(9, 3, 'fish-y')
            sheet18.write(9, 4, 'x')
            sheet18.write(9, 5, 'y')
            sheet18.write(9, 6, 'w')
            sheet18.write(9, 7, 'h')

        if int(HowMany) > 19:
            sheet19.write(0, 0, 'Exp Time')
            sheet19.write(0, 1, time.ctime())
            sheet19.write(1, 0, 'Tank #')
            sheet19.write(1, 1, '19')
            sheet19.write(2, 0, 'Fish Group')
            sheet19.write(3, 0, 'Fish ID')
            sheet19.write(4, 0, 'Fish DOB')
            sheet19.write(5, 0, 'Tank-P1')
            sheet19.write(5, 2, boxes[36][0])
            sheet19.write(5, 3, boxes[36][1])
            sheet19.write(6, 0, 'Tank-P2')
            sheet19.write(6, 2, boxes[37][0])
            sheet19.write(6, 3, boxes[37][1])
            sheet19.write(8, 0, 'x-y coordinates')
            sheet19.write(9, 0, 'Frame #')
            sheet19.write(9, 1, 'Timestamp')
            sheet19.write(9, 2, 'fish-x')
            sheet19.write(9, 3, 'fish-y')
            sheet19.write(9, 4, 'x')
            sheet19.write(9, 5, 'y')
            sheet19.write(9, 6, 'w')
            sheet19.write(9, 7, 'h')

        if int(HowMany) > 20:
            sheet20.write(0, 0, 'Exp Time')
            sheet20.write(0, 1, time.ctime())
            sheet20.write(1, 0, 'Tank #')
            sheet20.write(1, 1, '20')
            sheet20.write(2, 0, 'Fish Group')
            sheet20.write(3, 0, 'Fish ID')
            sheet20.write(4, 0, 'Fish DOB')
            sheet20.write(5, 0, 'Tank-P1')
            sheet20.write(5, 2, boxes[38][0])
            sheet20.write(5, 3, boxes[38][1])
            sheet20.write(6, 0, 'Tank-P2')
            sheet20.write(6, 2, boxes[39][0])
            sheet20.write(6, 3, boxes[39][1])
            sheet20.write(8, 0, 'x-y coordinates')
            sheet20.write(9, 0, 'Frame #')
            sheet20.write(9, 1, 'Timestamp')
            sheet20.write(9, 2, 'fish-x')
            sheet20.write(9, 3, 'fish-y')
            sheet20.write(9, 4, 'x')
            sheet20.write(9, 5, 'y')
            sheet20.write(9, 6, 'w')
            sheet20.write(9, 7, 'h')

        if int(HowMany) > 21:
            sheet21.write(0, 0, 'Exp Time')
            sheet21.write(0, 1, time.ctime())
            sheet21.write(1, 0, 'Tank #')
            sheet21.write(1, 1, '21')
            sheet21.write(2, 0, 'Fish Group')
            sheet21.write(3, 0, 'Fish ID')
            sheet21.write(4, 0, 'Fish DOB')
            sheet21.write(5, 0, 'Tank-P1')
            sheet21.write(5, 2, boxes[40][0])
            sheet21.write(5, 3, boxes[40][1])
            sheet21.write(6, 0, 'Tank-P2')
            sheet21.write(6, 2, boxes[41][0])
            sheet21.write(6, 3, boxes[41][1])
            sheet21.write(8, 0, 'x-y coordinates')
            sheet21.write(9, 0, 'Frame #')
            sheet21.write(9, 1, 'Timestamp')
            sheet21.write(9, 2, 'fish-x')
            sheet21.write(9, 3, 'fish-y')
            sheet21.write(9, 4, 'x')
            sheet21.write(9, 5, 'y')
            sheet21.write(9, 6, 'w')
            sheet21.write(9, 7, 'h')

        if int(HowMany) > 22:
            sheet22.write(0, 0, 'Exp Time')
            sheet22.write(0, 1, time.ctime())
            sheet22.write(1, 0, 'Tank #')
            sheet22.write(1, 1, '22')
            sheet22.write(2, 0, 'Fish Group')
            sheet22.write(3, 0, 'Fish ID')
            sheet22.write(4, 0, 'Fish DOB')
            sheet22.write(5, 0, 'Tank-P1')
            sheet22.write(5, 2, boxes[42][0])
            sheet22.write(5, 3, boxes[42][1])
            sheet22.write(6, 0, 'Tank-P2')
            sheet22.write(6, 2, boxes[43][0])
            sheet22.write(6, 3, boxes[43][1])
            sheet22.write(8, 0, 'x-y coordinates')
            sheet22.write(9, 0, 'Frame #')
            sheet22.write(9, 1, 'Timestamp')
            sheet22.write(9, 2, 'fish-x')
            sheet22.write(9, 3, 'fish-y')
            sheet22.write(9, 4, 'x')
            sheet22.write(9, 5, 'y')
            sheet22.write(9, 6, 'w')
            sheet22.write(9, 7, 'h')

        if int(HowMany) > 23:
            sheet23.write(0, 0, 'Exp Time')
            sheet23.write(0, 1, time.ctime())
            sheet23.write(1, 0, 'Tank #')
            sheet23.write(1, 1, '23')
            sheet23.write(2, 0, 'Fish Group')
            sheet23.write(3, 0, 'Fish ID')
            sheet23.write(4, 0, 'Fish DOB')
            sheet23.write(5, 0, 'Tank-P1')
            sheet23.write(5, 2, boxes[44][0])
            sheet23.write(5, 3, boxes[44][1])
            sheet23.write(6, 0, 'Tank-P2')
            sheet23.write(6, 2, boxes[45][0])
            sheet23.write(6, 3, boxes[45][1])
            sheet23.write(8, 0, 'x-y coordinates')
            sheet23.write(9, 0, 'Frame #')
            sheet23.write(9, 1, 'Timestamp')
            sheet23.write(9, 2, 'fish-x')
            sheet23.write(9, 3, 'fish-y')
            sheet23.write(9, 4, 'x')
            sheet23.write(9, 5, 'y')
            sheet23.write(9, 6, 'w')
            sheet23.write(9, 7, 'h')

        if int(HowMany) > 24:
            sheet24.write(0, 0, 'Exp Time')
            sheet24.write(0, 1, time.ctime())
            sheet24.write(1, 0, 'Tank #')
            sheet24.write(1, 1, '24')
            sheet24.write(2, 0, 'Fish Group')
            sheet24.write(3, 0, 'Fish ID')
            sheet24.write(4, 0, 'Fish DOB')
            sheet24.write(5, 0, 'Tank-P1')
            sheet24.write(5, 2, boxes[46][0])
            sheet24.write(5, 3, boxes[46][1])
            sheet24.write(6, 0, 'Tank-P2')
            sheet24.write(6, 2, boxes[47][0])
            sheet24.write(6, 3, boxes[47][1])
            sheet24.write(8, 0, 'x-y coordinates')
            sheet24.write(9, 0, 'Frame #')
            sheet24.write(9, 1, 'Timestamp')
            sheet24.write(9, 2, 'fish-x')
            sheet24.write(9, 3, 'fish-y')
            sheet24.write(9, 4, 'x')
            sheet24.write(9, 5, 'y')
            sheet24.write(9, 6, 'w')
            sheet24.write(9, 7, 'h')


    for row in range(rows):
        for col in range(1):
            if OnLineTracking == 2:
                if int(HowMany) > 1:
                    sheet1.write(row+10, col+0, data01[row][col])
                    sheet1.write(row+10, col+1, data01[row][col+1])
                    sheet1.write(row+10, col+1, data02[row][col+1])
                    sheet1.write(row+10, col+1, data03[row][col+1])
            else:
                if int(HowMany) > 1:
                    sheet1.write(row+10, col+0, data01[row][col])
                    sheet1.write(row+10, col+1, data01[row][col+1])
                    sheet1.write(row+10, col+2, data01[row][col+2])
                    sheet1.write(row+10, col+3, data01[row][col+3])
                    sheet1.write(row+10, col+4, data01[row][col+4])
                    sheet1.write(row+10, col+5, data01[row][col+5])
                    sheet1.write(row+10, col+6, data01[row][col+6])
                    sheet1.write(row+10, col+7, data01[row][col+7])
                if int(HowMany) > 2:
                    sheet2.write(row+10, col+0, data02[row][col])
                    sheet2.write(row+10, col+1, data02[row][col+1])
                    sheet2.write(row+10, col+2, data02[row][col+2])
                    sheet2.write(row+10, col+3, data02[row][col+3])
                    sheet2.write(row+10, col+4, data02[row][col+4])
                    sheet2.write(row+10, col+5, data02[row][col+5])
                    sheet2.write(row+10, col+6, data02[row][col+6])
                    sheet2.write(row+10, col+7, data02[row][col+7])
                if int(HowMany) > 3:
                    sheet3.write(row+10, col+0, data03[row][col])
                    sheet3.write(row+10, col+1, data03[row][col+1])
                    sheet3.write(row+10, col+2, data03[row][col+2])
                    sheet3.write(row+10, col+3, data03[row][col+3])
                    sheet3.write(row+10, col+4, data03[row][col+4])
                    sheet3.write(row+10, col+5, data03[row][col+5])
                    sheet3.write(row+10, col+6, data03[row][col+6])
                    sheet3.write(row+10, col+7, data03[row][col+7])
                if int(HowMany) > 4:
                    sheet4.write(row+10, col+0, data04[row][col])
                    sheet4.write(row+10, col+1, data04[row][col+1])
                    sheet4.write(row+10, col+2, data04[row][col+2])
                    sheet4.write(row+10, col+3, data04[row][col+3])
                    sheet4.write(row+10, col+4, data04[row][col+4])
                    sheet4.write(row+10, col+5, data04[row][col+5])
                    sheet4.write(row+10, col+6, data04[row][col+6])
                    sheet4.write(row+10, col+7, data04[row][col+7])
                if int(HowMany) > 5:
                    sheet5.write(row+10, col+0, data05[row][col])
                    sheet5.write(row+10, col+1, data05[row][col+1])
                    sheet5.write(row+10, col+2, data05[row][col+2])
                    sheet5.write(row+10, col+3, data05[row][col+3])
                    sheet5.write(row+10, col+4, data05[row][col+4])
                    sheet5.write(row+10, col+5, data05[row][col+5])
                    sheet5.write(row+10, col+6, data05[row][col+6])
                    sheet5.write(row+10, col+7, data05[row][col+7])
                if int(HowMany) > 6:
                    sheet6.write(row+10, col+0, data06[row][col])
                    sheet6.write(row+10, col+1, data06[row][col+1])
                    sheet6.write(row+10, col+2, data06[row][col+2])
                    sheet6.write(row+10, col+3, data06[row][col+3])
                    sheet6.write(row+10, col+4, data06[row][col+4])
                    sheet6.write(row+10, col+5, data06[row][col+5])
                    sheet6.write(row+10, col+6, data06[row][col+6])
                    sheet6.write(row+10, col+7, data06[row][col+7])
                if int(HowMany) > 7:
                    sheet7.write(row+10, col+0, data07[row][col])
                    sheet7.write(row+10, col+1, data07[row][col+1])
                    sheet7.write(row+10, col+2, data07[row][col+2])
                    sheet7.write(row+10, col+3, data07[row][col+3])
                    sheet7.write(row+10, col+4, data07[row][col+4])
                    sheet7.write(row+10, col+5, data07[row][col+5])
                    sheet7.write(row+10, col+6, data07[row][col+6])
                    sheet7.write(row+10, col+7, data07[row][col+7])
                if int(HowMany) > 8:
                    sheet8.write(row+10, col+0, data08[row][col])
                    sheet8.write(row+10, col+1, data08[row][col+1])
                    sheet8.write(row+10, col+2, data08[row][col+2])
                    sheet8.write(row+10, col+3, data08[row][col+3])
                    sheet8.write(row+10, col+4, data08[row][col+4])
                    sheet8.write(row+10, col+5, data08[row][col+5])
                    sheet8.write(row+10, col+6, data08[row][col+6])
                    sheet8.write(row+10, col+7, data08[row][col+7])
                if int(HowMany) > 9:
                    sheet9.write(row+10, col+0, data09[row][col])
                    sheet9.write(row+10, col+1, data09[row][col+1])
                    sheet9.write(row+10, col+2, data09[row][col+2])
                    sheet9.write(row+10, col+3, data09[row][col+3])
                    sheet9.write(row+10, col+4, data09[row][col+4])
                    sheet9.write(row+10, col+5, data09[row][col+5])
                    sheet9.write(row+10, col+6, data09[row][col+6])
                    sheet9.write(row+10, col+7, data09[row][col+7])
                if int(HowMany) > 10:
                    sheet10.write(row+10, col+0, data10[row][col])
                    sheet10.write(row+10, col+1, data10[row][col+1])
                    sheet10.write(row+10, col+2, data10[row][col+2])
                    sheet10.write(row+10, col+3, data10[row][col+3])
                    sheet10.write(row+10, col+4, data10[row][col+4])
                    sheet10.write(row+10, col+5, data10[row][col+5])
                    sheet10.write(row+10, col+6, data10[row][col+6])
                    sheet10.write(row+10, col+7, data10[row][col+7])
                if int(HowMany) > 11:
                    sheet11.write(row+10, col+0, data11[row][col])
                    sheet11.write(row+10, col+1, data11[row][col+1])
                    sheet11.write(row+10, col+2, data11[row][col+2])
                    sheet11.write(row+10, col+3, data11[row][col+3])
                    sheet11.write(row+10, col+4, data11[row][col+4])
                    sheet11.write(row+10, col+5, data11[row][col+5])
                    sheet11.write(row+10, col+6, data11[row][col+6])
                    sheet11.write(row+10, col+7, data11[row][col+7])
                if int(HowMany) > 12:
                    sheet12.write(row+10, col+0, data12[row][col])
                    sheet12.write(row+10, col+1, data12[row][col+1])
                    sheet12.write(row+10, col+2, data12[row][col+2])
                    sheet12.write(row+10, col+3, data12[row][col+3])
                    sheet12.write(row+10, col+4, data12[row][col+4])
                    sheet12.write(row+10, col+5, data12[row][col+5])
                    sheet12.write(row+10, col+6, data12[row][col+6])
                    sheet12.write(row+10, col+7, data12[row][col+7])
                if int(HowMany) > 13:
                    sheet13.write(row+10, col+0, data13[row][col])
                    sheet13.write(row+10, col+1, data13[row][col+1])
                    sheet13.write(row+10, col+2, data13[row][col+2])
                    sheet13.write(row+10, col+3, data13[row][col+3])
                    sheet13.write(row+10, col+4, data13[row][col+4])
                    sheet13.write(row+10, col+5, data13[row][col+5])
                    sheet13.write(row+10, col+6, data13[row][col+6])
                    sheet13.write(row+10, col+7, data13[row][col+7])
                if int(HowMany) > 14:
                    sheet14.write(row+10, col+0, data14[row][col])
                    sheet14.write(row+10, col+1, data14[row][col+1])
                    sheet14.write(row+10, col+2, data14[row][col+2])
                    sheet14.write(row+10, col+3, data14[row][col+3])
                    sheet14.write(row+10, col+4, data14[row][col+4])
                    sheet14.write(row+10, col+5, data14[row][col+5])
                    sheet14.write(row+10, col+6, data14[row][col+6])
                    sheet14.write(row+10, col+7, data14[row][col+7])
                if int(HowMany) > 15:
                    sheet15.write(row+10, col+0, data15[row][col])
                    sheet15.write(row+10, col+1, data15[row][col+1])
                    sheet15.write(row+10, col+2, data15[row][col+2])
                    sheet15.write(row+10, col+3, data15[row][col+3])
                    sheet15.write(row+10, col+4, data15[row][col+4])
                    sheet15.write(row+10, col+5, data15[row][col+5])
                    sheet15.write(row+10, col+6, data15[row][col+6])
                    sheet15.write(row+10, col+7, data15[row][col+7])
                if int(HowMany) > 16:
                    sheet16.write(row+10, col+0, data16[row][col])
                    sheet16.write(row+10, col+1, data16[row][col+1])
                    sheet16.write(row+10, col+2, data16[row][col+2])
                    sheet16.write(row+10, col+3, data16[row][col+3])
                    sheet16.write(row+10, col+4, data16[row][col+4])
                    sheet16.write(row+10, col+5, data16[row][col+5])
                    sheet16.write(row+10, col+6, data16[row][col+6])
                    sheet16.write(row+10, col+7, data16[row][col+7])
                if int(HowMany) > 17:
                    sheet17.write(row+10, col+0, data17[row][col])
                    sheet17.write(row+10, col+1, data17[row][col+1])
                    sheet17.write(row+10, col+2, data17[row][col+2])
                    sheet17.write(row+10, col+3, data17[row][col+3])
                    sheet17.write(row+10, col+4, data17[row][col+4])
                    sheet17.write(row+10, col+5, data17[row][col+5])
                    sheet17.write(row+10, col+6, data17[row][col+6])
                    sheet17.write(row+10, col+7, data17[row][col+7])
                if int(HowMany) > 18:
                    sheet18.write(row+10, col+0, data18[row][col])
                    sheet18.write(row+10, col+1, data18[row][col+1])
                    sheet18.write(row+10, col+2, data18[row][col+2])
                    sheet18.write(row+10, col+3, data18[row][col+3])
                    sheet18.write(row+10, col+4, data18[row][col+4])
                    sheet18.write(row+10, col+5, data18[row][col+5])
                    sheet18.write(row+10, col+6, data18[row][col+6])
                    sheet18.write(row+10, col+7, data18[row][col+7])
                if int(HowMany) > 19:
                    sheet19.write(row+10, col+0, data19[row][col])
                    sheet19.write(row+10, col+1, data19[row][col+1])
                    sheet19.write(row+10, col+2, data19[row][col+2])
                    sheet19.write(row+10, col+3, data19[row][col+3])
                    sheet19.write(row+10, col+4, data19[row][col+4])
                    sheet19.write(row+10, col+5, data19[row][col+5])
                    sheet19.write(row+10, col+6, data19[row][col+6])
                    sheet19.write(row+10, col+7, data19[row][col+7])
                if int(HowMany) > 20:
                    sheet20.write(row+10, col+0, data20[row][col])
                    sheet20.write(row+10, col+1, data20[row][col+1])
                    sheet20.write(row+10, col+2, data20[row][col+2])
                    sheet20.write(row+10, col+3, data20[row][col+3])
                    sheet20.write(row+10, col+4, data20[row][col+4])
                    sheet20.write(row+10, col+5, data20[row][col+5])
                    sheet20.write(row+10, col+6, data20[row][col+6])
                    sheet20.write(row+10, col+7, data20[row][col+7])
                if int(HowMany) > 21:
                    sheet21.write(row+10, col+0, data21[row][col])
                    sheet21.write(row+10, col+1, data21[row][col+1])
                    sheet21.write(row+10, col+2, data21[row][col+2])
                    sheet21.write(row+10, col+3, data21[row][col+3])
                    sheet21.write(row+10, col+4, data21[row][col+4])
                    sheet21.write(row+10, col+5, data21[row][col+5])
                    sheet21.write(row+10, col+6, data21[row][col+6])
                    sheet21.write(row+10, col+7, data21[row][col+7])
                if int(HowMany) > 22:
                    sheet22.write(row+10, col+0, data22[row][col])
                    sheet22.write(row+10, col+1, data22[row][col+1])
                    sheet22.write(row+10, col+2, data22[row][col+2])
                    sheet22.write(row+10, col+3, data22[row][col+3])
                    sheet22.write(row+10, col+4, data22[row][col+4])
                    sheet22.write(row+10, col+5, data22[row][col+5])
                    sheet22.write(row+10, col+6, data22[row][col+6])
                    sheet22.write(row+10, col+7, data22[row][col+7])
                if int(HowMany) > 23:
                    sheet23.write(row+10, col+0, data23[row][col])
                    sheet23.write(row+10, col+1, data23[row][col+1])
                    sheet23.write(row+10, col+2, data23[row][col+2])
                    sheet23.write(row+10, col+3, data23[row][col+3])
                    sheet23.write(row+10, col+4, data23[row][col+4])
                    sheet23.write(row+10, col+5, data23[row][col+5])
                    sheet23.write(row+10, col+6, data23[row][col+6])
                    sheet23.write(row+10, col+7, data23[row][col+7])
                if int(HowMany) > 24:
                    sheet24.write(row+10, col+0, data24[row][col])
                    sheet24.write(row+10, col+1, data24[row][col+1])
                    sheet24.write(row+10, col+2, data24[row][col+2])
                    sheet24.write(row+10, col+3, data24[row][col+3])
                    sheet24.write(row+10, col+4, data24[row][col+4])
                    sheet24.write(row+10, col+5, data24[row][col+5])
                    sheet24.write(row+10, col+6, data24[row][col+6])
                    sheet24.write(row+10, col+7, data24[row][col+7])

    #book.save("D:\\Vertical Assay\\EMBLarval_Excel\\" + GroupName + "\\TrackingData_" + GroupName + "_" + tt961 + "_" + ('%04d' % tt96) + "_Raw.xlsx")
    book.close()
    ImageGrab.grab().save("D:\\Vertical Assay\\EMBLarval_Excel\\" + GroupName + "\\Screen_" + tt961 + ".jpg", "JPEG")

